### ISSUE TITLE
Example in-band-network-telemetry

### ISSUE THREAD

**Issue by fernandodebrando** [kevinbird61/p4-researching#21]
I'm testing the example of in-band-network-telemetry but `pingall` does not work. Can you give me an example of execution?

**Comment by kevinbird61** [comment]
The INT example in this repository is not completed ( lack of testing environments, e.g. virtual network topology) . 
Here are some examples that worth reference:
* https://github.com/coolvikas/P4_INT
* https://github.com/MehmedGIT/INT-InBand-Network-Telemetry-
Hope that will help!

**Comment by fernandodebrando** [comment]
Thanks!
