### ISSUE TITLE
learning switch loop after multiple switches

### ISSUE THREAD

**Issue by Vuk0dlak** [kevinbird61/p4-researching#27]
Greetings, 

I am using your p4 learning switch program, but I have a problem regarding the multicast action. When I try to add another switch in the topology, I confront with loops. What is the meaning of the multicast in your controller and do you know if I can avoid the loops?

Regards

Adonis Chatzivasiliou

**Comment by kevinbird61** [comment]
Hi Adonis,

Do you mean the MPLS in this repository? If yes, how did you add the new switch in the [topology](https://github.com/kevinbird61/p4-researching/blob/master/src/fundamental/mpls/res/mpls.png) ? 
The controller in this example is to insert the rule for label of mpls, you can insert the new rule to avoid the loop.

Thanks, 
Kevin Cyu

**Comment by Vuk0dlak** [comment]
Hello Kevin,
Thanks for the respond,
I do  not mean the mpls exercise, I have tried the learning switch exercise (The one you are using Packet in Packet out) . I would like to say that with your current topology all seems to working properly. When I add another switch (s2) direct to s1 then i confront of loops. 

Furthermore I dont understand in line 125 of the p4runtime controller 
( https://github.com/kevinbird61/p4-researching/blob/819a4cd2dba417e27b4e7602651d29da9dfe8c09/src/fundamental/learning-switch/p4_controller.py#L125 )
the Id :1 i think it represents Mac address and Id:2 represents port. Am i wrong? Do you know how Can I avoid the loops?

Best regards

Antonis Chatzivasiliou

**Comment by kevinbird61** [comment]
Hi Antonis,

Sorry for the naming mistake, this is not how ARP works, it just offloading l2 learning function from switch to controller.
After looking at the code, I find it may cause some mistake when you want to add one more switch.

Structure of packet out is defined [here](https://github.com/kevinbird61/p4-researching/blob/819a4cd2db/src/fundamental/learning-switch/includes/headers.p4#L20):
```p4
@controller_header("packet_out")
header packet_out_header_t {
    bit<16> egress_port;
    bit<16> mcast_grp;
}
```
- first is `egress port`, and second is `mcast_grp`.

In this learning switch exercise, controller will receive the packet in from s1, and then send packet out back to s1. If controller find this packet is a broadcast packet, the `egress port` will be 0 and `mcast_grp` will be 1 in  `packet out` and install the flooding rule ( [writeARPFlood](https://github.com/kevinbird61/p4-researching/blob/819a4cd2dba417e27b4e7602651d29da9dfe8c09/src/fundamental/learning-switch/p4_controller.py#L34)), And our controller has installed the multicast group on s1 in [line 87](https://github.com/kevinbird61/p4-researching/blob/819a4cd2dba417e27b4e7602651d29da9dfe8c09/src/fundamental/learning-switch/p4_controller.py#L87), so in this case this packet will be flooded to each host. 
Another case, if is not bcast packet, controller will maintain a key-value pair table to store the mac address as key and corresponding port  as value, if matched, it will store this port into `egress port` into `packet out` (and in this case, `mcast_grp` will not be used) and send back to s1, also install rule ([writeARPReply](https://github.com/kevinbird61/p4-researching/blob/819a4cd2dba417e27b4e7602651d29da9dfe8c09/src/fundamental/learning-switch/p4_controller.py#L20)) on s1 for matching and sending to correct host. 

When I write this example, I'm not familiar with "switching" and "routing", so the code look bad.
If you want to have another switch on it, you might need to separate the multicast group or modify it with correct switching behavior to avoid the loop.

Thanks,
Kevin Cyu

**Comment by Vuk0dlak** [comment]
I forgot to close the issue...

Thank you very much for your response
