### ISSUE TITLE
Tutorials or Courses

### ISSUE THREAD

**Issue by kevinbird61** [kevinbird61/p4-researching#3]
Any tutorials or courses are welcome, too! 
You can create a folder under `courses/<your_tutorals_or_courses_name>` for your precious materials!

**Comment by shravankumar9892** [comment]
Hey would you focus only on p4 or will you extend this research into different domains/languages ?

**Comment by kevinbird61** [comment]
Oh yes, currently focus on P4, aim to familiar with this language and develop roadmap.
After that, I will start working on DPI + p4 , and my friend @yungshenglu will start working on NN + p4. (at least now)

**Comment by shravankumar9892** [comment]
I'm good at NN, but I'm completely unaware of p4. I'm well versed with TensorFlow, Keras, sklearn, OpenCV, skimage, etc. basically Computer Vision. Can I help y'all?
